language: c++
install:
  - hg clone https://bitbucket.org/eigen/eigen/ && cd eigen && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && sudo make install
compiler:
  - clang
  - gcc
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
