language: c++
install:
  - hg clone https://bitbucket.org/eigen/eigen/
  - pushd eigen && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && sudo make install  && popd
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
script:
  - make

