language: c++
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - hg clone https://bitbucket.org/eigen/eigen/
  - pushd eigen && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && sudo make install  && popd
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
script:
  - make

